Merged dev with release-1.2.0 branch
mosip/pre-registration pull request #497
Opened 2022-02-11 11:01 UTC by mayuradesh

2022-02-11 14:30 UTC, gsasikumar requested changes

2022-02-11 14:30 UTC, gsasikumar commented on README.md
> +[![Maven Package upon a push](https://github.com/mosip/pre-registration/actions/workflows/push_trigger.yml/badge.svg?branch=release-1.2.0)](https://github.com/mosip/pre-registration/actions/workflows
Branch name has to be changed to develop

2022-02-11 14:30 UTC, gsasikumar commented on README.md
> +[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?branch=release-1.2.0&project=mosip_pre-registration&metric=alert_status)](https://sonarcloud.io/dashboard?branch=release-1.2.0
branch name has to be changed to develop

2022-02-13 06:27 UTC, ckm007 reviewed
Can see difference in db scripts and all... can we confirm ifthe same changes are not part of develop... as they should have everything commons except Readme, .github files and few plugins additions

2022-02-14 05:03 UTC, mayuradesh commented
> Can see difference in db scripts and all... can we confirm ifthe same changes are not part of develop... as they should have everything commons except Readme, .github files and few plugins additions

As discussed with Mandeep, all the new db changes have to be moved from "release-1.2.0" branch to "develop".

2022-02-14 05:03 UTC, mayuradesh commented on README.md
> +[![Quality Gate Status](https://sonarcloud.io/api/project_badges/measure?branch=release-1.2.0&project=mosip_pre-registration&metric=alert_status)](https://sonarcloud.io/dashboard?branch=release-1.2.0
done

2022-02-14 05:07 UTC, mayuradesh commented on README.md
> +[![Maven Package upon a push](https://github.com/mosip/pre-registration/actions/workflows/push_trigger.yml/badge.svg?branch=release-1.2.0)](https://github.com/mosip/pre-registration/actions/workflows
done

2022-02-14 05:29 UTC, merged