[MOSIP-34305] Pre reg api test case description addition
mosip/pre-registration pull request #691
Opened 2024-07-05 14:36 UTC by gopalaswin

Added description for following APIs

SendOtp
ValidateOtp
CreatePreregistration

2024-07-18 10:07 UTC, gopalaswin commented
[MOSIP-3430] Pre reg api test case description addition
For the above commit, I updated the descriptions for the following APIs:
1. SENT OTP 
2.  ValidateOtp
3. CreatePreregistration
4. UpdatePreregistration
5. GetApplicationWithPrId
6. FetchApplicationByPrid 
7. GetApplicationStatusWithPrId
8. Uploaddocument 
9. UpdateDocRefID
10. CopyDocument
11. UpdatePreRegStatus
12. GetAllDocForPrId
13. GetPRIDByDateRange
14. BookAppointment
15. FetchAppointmentDetailsByPrid 
16. BookAppointmentByPRID
17. GetAppointmentDetails 
18. CancelAppointment 
19. CancelApplicationsAppointment
20.  GetAvailableSlotForRegCentreId
21. GetBookingsForRegCenter
22. GetPRIDForRegCent 
23. SendNotifications 
24.  DeleteSpecificDocForaPRID
25. DeleteAllDocForaPRID 
26. DeleteBooking 
27. InvalidateToken 
28. Transliteration 
29. GetAllApplications 
30. GetAllApplicationsWithapplicationId
31. GetUpdatedDateTimeByPrid
32. AddUpdateRegistration
33. AddLostUinApplication 
34. DeleteLostUinApplication
35. DeletePreRegistration 
36. GetPreRegInfo
37. GetAllPreRegApplications

2024-07-25 05:44 UTC, Sohandey requested changes
apitest/src/main/resources/preReg/FetchApplicationByPrid/FetchApplicationByPrid.yml
"preRegistrationId": "59286406501581"
  "preRegistrationId": "59286406501581
  
  a double qoute is missing in the end 
  
 and please try to complete the description in a single line

2024-08-06 11:23 UTC, Sohandey approved these changes

2024-08-08 05:18 UTC, Sohandey approved these changes

2024-08-08 10:16 UTC, lsivanand approved these changes

2024-08-13 13:21 UTC, mayuradesh approved these changes

2024-08-13 13:32 UTC, merged