MOSIP-33036 - Added upgrade and rollback scripts for release-1.3.x
mosip/pre-registration pull request #719
Opened 2024-09-03 13:40 UTC by GOKULRAJ136

2024-09-04 05:43 UTC, dhanendra06 approved these changes

2024-09-04 08:04 UTC, mayuradesh requested changes
Please get it reviewed and update me

2024-09-04 08:26 UTC, ase-101 commented
@GOKULRAJ136 - what was our previous spring-batch version?

2024-09-04 08:50 UTC, GOKULRAJ136 commented
> @GOKULRAJ136 - what was our previous spring-batch version?

The previous version of Spring Batch we used was 2.0.2.RELEASE.

2024-09-05 06:55 UTC, ase-101 approved these changes

2024-09-10 05:37 UTC, mayuradesh approved these changes

2024-09-10 05:37 UTC, merged