MOSIP-35959 updated uniqueIdentifier for Pre-reg
mosip/pre-registration pull request #738
Opened 2024-10-09 13:16 UTC by gopalaswin

2024-10-10 05:51 UTC, mohanachandran-s requested changes

2024-10-10 05:51 UTC, mohanachandran-s commented on api-test/src/main/resources/preReg/ValidateOtp/ValidateOtp.yml
> +	uniqueIdentifier: TC_prereg_ValidateOtp_02
Correct the indentation and check the same in entire PR

2024-10-10 07:06 UTC, mohanachandran-s approved these changes

2024-10-18 05:20 UTC, mayuradesh approved these changes

2024-10-18 07:53 UTC, mayuradesh approved these changes

2024-10-18 08:04 UTC, merged